### ISSUE TITLE
Q: How to add custom images/icons for toolbar builder via image path

### ISSUE THREAD

**Issue by avinash-ramireddy** [XAM-Consulting/TEditor#15]
Hi,
I am unable to add image of my own. 
Should those be added in drawable*(hdpi,xdpi,xxdpi...) and Resource(in iOS) or should we specify them in PCL?

It is throwing unhandled exception.

**Comment by jessejiang0214** [comment]
Just like add a normal image to Xamrin.Forms project. Put the image into iOS and Android project with the same name. Then call 
 var toolbar = new ToolbarBuilder().AddBasic().AddH1("H1Icon.png");
API to do that

**Comment by avinash-ramireddy** [comment]
I did same. I have added different type of images of size(30,60,90) for both android and ios.

But when I run it is throwing unhandled exception at image path...

I will try to reproduce issue...

**Comment by avinashramireddy-rapidd** [comment]
I did. I have added images of size 30,60,90 both for droid and ios.

But I am getting unhandled exception...I will try to reproduce the issue when I get time
