### ISSUE TITLE
Focusing the editor input field (Xamarin.Forms)

### ISSUE THREAD

**Issue by Dids** [XAM-Consulting/TEditor#22]
Having the abililty either manually or automatically (on `ShowTEditor()` for instance) focus the editor input field is something I'd definitely love to see and actually have a need for.

Any chance of getting this or can you alternatively think of a workaround? Subclassing the editor or something?

**Comment by jessejiang0214** [comment]
You need to change source code of TEditorActivity and TEditorViewController
