### ISSUE TITLE
Editor Title

### ISSUE THREAD

**Issue by swansca79** [XAM-Consulting/TEditor#4]
There should be a property to set Title instead of the hardcoding 'HTML Editor'.

**Comment by Brosten** [comment]
Is this still an open issue? We'd like to use this Control, but the hard-coded texts is a problem because of need for translation. Any plans to fix it in the main branch?

**Comment by jessejiang0214** [comment]
Fixed in 1.0.1
`CrossTEditor.PageTitle = "Title";`
